name: Publish artifacts
description: Publish artifacts

runs:
  using: composite
  steps:
  - name: 游닌 Collect artifacts
    run: tools/artifacts/_stage_all.ps1
    shell: pwsh
    if: always()

# TODO: replace this hard-coded list with a loop that utilizes the NPM package at
# https://github.com/actions/toolkit/tree/main/packages/artifact (or similar) to push the artifacts.

  - name: 游닉 Upload project.assets.json files
    if: always()
    uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
    with:
      name: projectAssetsJson-${{ runner.os }}
      path: ${{ runner.temp }}/_artifacts/projectAssetsJson
    continue-on-error: true
  - name: 游닉 Upload variables
    uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
    with:
      name: variables-${{ runner.os }}
      path: ${{ runner.temp }}/_artifacts/Variables
    continue-on-error: true
  - name: 游닉 Upload build_logs
    if: always()
    uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
    with:
      name: build_logs-${{ runner.os }}
      path: ${{ runner.temp }}/_artifacts/build_logs
    continue-on-error: true
  - name: 游닉 Upload testResults
    if: always()
    uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
    with:
      name: testResults-${{ runner.os }}
      path: ${{ runner.temp }}/_artifacts/testResults
    continue-on-error: true
  - name: 游닉 Upload coverageResults
    if: always()
    uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
    with:
      name: coverageResults-${{ runner.os }}
      path: ${{ runner.temp }}/_artifacts/coverageResults
    continue-on-error: true
  - name: 游닉 Upload symbols
    uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
    with:
      name: symbols-${{ runner.os }}
      path: ${{ runner.temp }}/_artifacts/symbols
    continue-on-error: true
  - name: 游닉 Upload deployables
    uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
    with:
      name: deployables-${{ runner.os }}
      path: ${{ runner.temp }}/_artifacts/deployables
    if: always()
