// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658
namespace Windows.Win32
{
	using global::System;
	using global::System.Diagnostics;
	using global::System.Runtime.CompilerServices;
	using global::System.Runtime.InteropServices;
	using global::System.Runtime.Versioning;
	using win32 = global::Windows.Win32;

	namespace Storage.FileSystem
	{
		internal enum FILE_CREATION_DISPOSITION : uint
		{
			CREATE_NEW = 1U,
			CREATE_ALWAYS = 2U,
			OPEN_EXISTING = 3U,
			OPEN_ALWAYS = 4U,
			TRUNCATE_EXISTING = 5U,
		}
	}
}
