// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658
namespace Windows.Win32
{
	using global::System;
	using global::System.Diagnostics;
	using global::System.Runtime.CompilerServices;
	using global::System.Runtime.InteropServices;
	using win32 = global::Windows.Win32;

	namespace Storage.FileSystem
	{
		[Flags]
		internal enum FILE_ACCESS_FLAGS : uint
		{
			FILE_READ_DATA = 0x00000001,
			FILE_LIST_DIRECTORY = 0x00000001,
			FILE_WRITE_DATA = 0x00000002,
			FILE_ADD_FILE = 0x00000002,
			FILE_APPEND_DATA = 0x00000004,
			FILE_ADD_SUBDIRECTORY = 0x00000004,
			FILE_CREATE_PIPE_INSTANCE = 0x00000004,
			FILE_READ_EA = 0x00000008,
			FILE_WRITE_EA = 0x00000010,
			FILE_EXECUTE = 0x00000020,
			FILE_TRAVERSE = 0x00000020,
			FILE_DELETE_CHILD = 0x00000040,
			FILE_READ_ATTRIBUTES = 0x00000080,
			FILE_WRITE_ATTRIBUTES = 0x00000100,
			READ_CONTROL = 0x00020000,
			SYNCHRONIZE = 0x00100000,
			STANDARD_RIGHTS_REQUIRED = 0x000F0000,
			STANDARD_RIGHTS_READ = 0x00020000,
			STANDARD_RIGHTS_WRITE = 0x00020000,
			STANDARD_RIGHTS_EXECUTE = 0x00020000,
			STANDARD_RIGHTS_ALL = 0x001F0000,
			SPECIFIC_RIGHTS_ALL = 0x0000FFFF,
			FILE_ALL_ACCESS = 0x001F01FF,
			FILE_GENERIC_READ = 0x00120089,
			FILE_GENERIC_WRITE = 0x00120116,
			FILE_GENERIC_EXECUTE = 0x001200A0,
		}
	}
}
