// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658
namespace Windows.Win32
{
	using global::System;
	using global::System.Diagnostics;
	using global::System.Runtime.CompilerServices;
	using global::System.Runtime.InteropServices;
	using win32 = global::Windows.Win32;

	namespace Foundation
	{
		[DebuggerDisplay("{Value}")]
		internal readonly partial struct HWND
			: IEquatable<HWND>
		{
			internal readonly nint Value;
			internal HWND(nint value) => this.Value = value;
			public static implicit operator nint(HWND value) => value.Value;
			public static explicit operator HWND(nint value) => new HWND(value);
			public static bool operator ==(HWND left, HWND right) => left.Value == right.Value;
			public static bool operator !=(HWND left, HWND right) => !(left == right);

			public bool Equals(HWND other) => this.Value == other.Value;

			public override bool Equals(object obj) => obj is HWND other && this.Equals(other);

			public override int GetHashCode() => this.Value.GetHashCode();
		}
	}
}
